import Head from 'next/head'
import Image from 'next/image'
import MainPage from '../components/MainPage'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container mx-auto'>
        <Navbar/>
        <MainPage/>
      </div>
    </>
  )
}
